import React from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, AlertTriangle, Zap } from 'lucide-react';
import { useSmartHealth } from '../context/SmartHealthContext';

const URGENCY_CONFIG = {
  Critical: { color: 'border-red-500/40 bg-red-500/8', badge: 'badge-danger', dot: 'bg-red-400' },
  High: { color: 'border-orange-500/40 bg-orange-500/8', badge: 'badge-warning', dot: 'bg-orange-400' },
  Medium: { color: 'border-yellow-500/40 bg-yellow-500/8', badge: 'badge-warning', dot: 'bg-yellow-400' },
};

export default function RedistributionCard({ recommendations = [] }) {
  const { createTransfer } = useSmartHealth();

  if (recommendations.length === 0) {
    return (
      <div className="glass-card p-8 text-center">
        <Zap className="w-10 h-10 mx-auto mb-3 text-primary-400 opacity-60" />
        <p className="text-white/60 font-semibold">No redistribution needed</p>
        <p className="text-sm text-white/30 mt-1">All hospitals have adequate stock levels</p>
      </div>
    );
  }

  return (
    <div className="space-y-3">
      {recommendations.map((rec, i) => {
        const cfg = URGENCY_CONFIG[rec.urgency] || URGENCY_CONFIG.Medium;
        return (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.08 }}
            className={`glass-card-sm border ${cfg.color} p-5`}
          >
            <div className="flex items-center gap-2 mb-4">
              <span className={`w-2 h-2 rounded-full ${cfg.dot}`} />
              <span className={cfg.badge}>{rec.urgency}</span>
              <span className="text-sm font-bold text-white">{rec.medicine_name}</span>
            </div>

            {/* Transfer visualization */}
            <div className="flex items-center gap-3">
              {/* Donor hospital */}
              <div className="flex-1 glass-card-sm p-3 border border-emerald-500/20 bg-emerald-500/5">
                <p className="text-xs text-white/40 mb-1">SURPLUS FROM</p>
                <p className="text-sm font-bold text-white truncate">{rec.from_hospital_name}</p>
                <p className="text-xs text-emerald-400 font-semibold mt-1">
                  Stock: {rec.from_hospital_stock} units
                </p>
              </div>

              {/* Arrow + quantity */}
              <div className="flex flex-col items-center gap-1 flex-shrink-0">
                <ArrowRight className="w-5 h-5 text-primary-400" />
                <div className="text-xs font-bold text-primary-400 bg-primary-500/20 px-2 py-0.5 rounded-full border border-primary-500/30">
                  {rec.recommended_transfer_qty}
                </div>
              </div>

              {/* Needy hospital */}
              <div className="flex-1 glass-card-sm p-3 border border-red-500/20 bg-red-500/5">
                <p className="text-xs text-white/40 mb-1">NEEDED AT</p>
                <p className="text-sm font-bold text-white truncate">{rec.to_hospital_name}</p>
                <p className="text-xs text-red-400 font-semibold mt-1">
                  Stock: {rec.to_hospital_stock} units
                </p>
              </div>
            </div>

            {/* Action */}
            <div className="mt-4 flex items-center justify-between">
              <p className="text-xs text-white/40 italic">Generated by AI Redistribution Engine</p>
              <button 
                onClick={async () => {
                  try {
                    await createTransfer({
                      item_name: rec.medicine_name,
                      quantity: rec.recommended_transfer_qty,
                      from_hospital: rec.from_hospital_id,
                      to_hospital: rec.to_hospital_id
                    });
                    // Refresh data or show success
                    alert('Transfer initiated! Waiting for CHC to dispatch.');
                  } catch (e) {
                    alert('Failed to initiate transfer');
                  }
                }}
                className="btn-primary text-xs px-4 py-2 flex items-center gap-1.5"
              >
                <Zap className="w-3.5 h-3.5" />
                Initiate Transfer
              </button>
            </div>
          </motion.div>
        );
      })}
    </div>
  );
}
